name: Check cloudformation linting and build docs

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install mkdocs
      run: |
        pip3 install mkdocs mkdocs-material
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup cloudformation linter
      uses: ScottBrenner/cfn-lint-action@v2.2.1
    - name: Run cloudformation lint
      run: cfn-lint -t stack.yaml
    - name: Build docs
      run: |
        cd docs;
        mkdocs build;
        cd ..;
        rm -rf site
        mkdir -p site;
        mv docs/site site/docs;
        echo "<meta http-equiv=\"refresh\" content=\"0; url=/4.0/\">" > site/index.html;
