name: Build and deploy blog.vapor.codes

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install mkdocs
      run: |
        pip3 install mkdocs mkdocs-material
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Site
      run: |
        cd docs;
        mkdocs build;
        cd ..;
        rm -rf site
        mkdir -p site;
        mv docs/site site/docs;
        echo "<meta http-equiv=\"refresh\" content=\"0; url=/4.0/\">" > site/index.html;
    - name: Configure AWS credentials
      id: cred
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DOCS_DEPLOYER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-2'
    - name: Deploy to AWS Cloudformation
      id: clouddeploy
      uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
      with:
        name: vapor-docs-de-stack
        template: stack.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          DomainName=de.docs.vapor.codes,
          S3BucketName=vapor-docs-de-site,
          AcmCertificateArn=${{ secrets.CERTIFICATE_ARN }}
      if: steps.cred.outcome == 'success'
    - name: Deploy to S3
      id: s3deploy
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'vapor-docs-de-site'
        AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOYER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: 'Output'
      if: steps.clouddeploy.outcome == 'success'
    - name: Invalidate CloudFront
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/*'
        AWS_REGION: 'eu-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOYER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DE_DOCS_DISTRIBUTION_ID }}
